### ISSUE TITLE
Can use LTE China Telecom but can't call other.

### ISSUE THREAD

**Issue by XinoAssassin** [PeterCxy/LockNetworkType#1]
System: CM 12.1 20151117-SNAPSHOT
（只是为了报个bug这个坑修不修无所谓用不来英文描述问题）
设备跟你的的一样是国行版本，插电信卡用该模块锁了LTE/CDMA auto (PRL)之后信号为LTE，但是无法通话，具体表现为回落失败。

**Comment by qa2080639** [comment]
can you add "LTE/CDMA/EvDo auto (PRL)" model  for china telecom?

**Comment by PeterCxy** [comment]
@qa2080639 There is no way I could do this. This module only locks the current network mode to an existing mode in the OS.

**Comment by PeterCxy** [comment]
@XiDeAssassin I can do nothing for this. This is only a module to lock the network mode, which does not implement support for any kind of telephony network. Contact the ROM developers for fixing this.
